**Create a Rank 1 ndarray**

In [2]:
import numpy as np
arr1 = np.array([11,12,13])
print (arr1)
print (type(arr1))
print (arr1.shape)
print (arr1[0])

[11 12 13]
<class 'numpy.ndarray'>
(3,)
11


In [4]:
arr1[1] = 55
print (arr1)

[11 55 13]


**Create a Rank 2 ndarray**

In [5]:
arr2 = np.array([[11,12,13],[21,22,23]])
print (arr2)
print (type(arr2))
print (arr2.shape)
print (arr2[1,0])

[[11 12 13]
 [21 22 23]]
<class 'numpy.ndarray'>
(2, 3)
21


**Built in ways to create ndarray**

In [7]:
ex1 = np.zeros((2,2))
print (ex1)

[[0. 0.]
 [0. 0.]]


In [8]:
ex2 = np.zeros((3,3))
print (ex2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
ex3 = np.full((2,2), 9.0)
print (ex3)

[[9. 9.]
 [9. 9.]]


In [13]:
ex4 = np.ones((1,2))
print (ex4)
print (ex4.shape)

[[1. 1.]]
(1, 2)


In [15]:
ex5 = np.eye(3,3)
print (ex5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
ex6 = np.random.random((2,2))
print (ex6)

[[0.31072245 0.28869263]
 [0.22040238 0.3711139 ]]


**Slice indexing**

In [25]:
x = np.array([[11,12,13],[21,22,23],[31,32,33]])
print (x);

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [30]:
x_slice = x[:2,1:3]
x_slice2 = x[0:2,1:3]
print (x_slice)
print (x_slice2)
print (x[0,0])

[[  12   13]
 [1000   23]]
[[  12   13]
 [1000   23]]
11


In [27]:
print (x)
print (x_slice)
x_slice[1,0] = 1000
print (x)
print (x_slice)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[12 13]
 [22 23]]
[[  11   12   13]
 [  21 1000   23]
 [  31   32   33]]
[[  12   13]
 [1000   23]]


**Slice and Integer indexing**

In [35]:
a = np.array([[11,12,13],[21,22,23],[31,32,33]])
a_rank1 = a[1,:]
a_rank2 = a[1:2, :]
print (a_rank1)
print (a_rank1.shape)
print (a_rank2)
print (a_rank2.shape)

[21 22 23]
(3,)
[[21 22 23]]
(1, 3)


In [36]:
col_rank1 = a[:,1]
col_rank2 = a[:,1:2]
print (col_rank1)
print (col_rank1.shape)
print (col_rank2)
print (col_rank2.shape)

[12 22 32]
(3,)
[[12]
 [22]
 [32]]
(3, 1)


**Array indexing for changing elements**

In [46]:
orig = np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print ('orig array : ')
print (orig)
col_indices = np.array([0,1,2,0])
print ('col_indices : ', col_indices)
row_indices = np.arange(4)
print ('row_indices :', row_indices)

orig array : 
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
col_indices :  [0 1 2 0]
row_indices : [0 1 2 3]


In [40]:
for row,col in zip(row_indices,col_indices):
    print(row," ", col)

0   0
1   1
2   2
3   0


In [43]:
print('values of orig array at those indices: ', orig[row_indices,col_indices])

values of orig array at those indices:  [11 22 33 41]


In [47]:
orig[row_indices,col_indices] += 10000
print ('changed array :')
print ( orig)

changed array :
[[10011    12    13]
 [   21 10022    23]
 [   31    32 10033]
 [10041    42    43]]


**Boolean indexing**

In [52]:
bool_arr = np.array([[11,12,13],[21,22,23],[31,32,33]])
print (bool_arr)


[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [53]:
filter = (bool_arr>15)
print (filter)
print (filter.shape)

[[False False False]
 [ True  True  True]
 [ True  True  True]]
(3, 3)


In [54]:
print (bool_arr[filter])

[21 22 23 31 32 33]


In [55]:
print (bool_arr[(bool_arr % 2 ==0)])

[12 22 32]


In [56]:
bool_arr [(bool_arr % 2 == 0)] += 100
print (bool_arr)

[[ 11 112  13]
 [ 21 122  23]
 [ 31 132  33]]


**Datatypes**

In [58]:
ex1 = np.array([[11,12],[21,22]])
print (ex1.dtype)

int64


In [59]:
ex2 = np.array([11.2, 22.3])
print (ex2.dtype)

float64


In [60]:
ex3 = np.array([11.2,22.3], dtype = np.int64)
print (ex3.dtype)

int64


In [62]:
ex4 = np.array([11,22], dtype = np.float64)
print (ex4)
print (ex4.dtype)

[11. 22.]
float64


**Arithmetic array operations**

In [65]:
x = np.array([[11,22],[23,44]], dtype = np.int64)
y = np.array([[55.1,66.1],[77.1,88.1]], dtype = np.float64)
print (x)
print (y)

[[11 22]
 [23 44]]
[[55.1 66.1]
 [77.1 88.1]]


In [66]:
print (x+y)
print(np.add(x,y))

[[ 66.1  88.1]
 [100.1 132.1]]
[[ 66.1  88.1]
 [100.1 132.1]]


In [67]:
print (x-y)
print(np.subtract(x,y))

[[-44.1 -44.1]
 [-54.1 -44.1]]
[[-44.1 -44.1]
 [-54.1 -44.1]]


In [68]:
print (x*y)
print (np.multiply(x,y))

[[ 606.1 1454.2]
 [1773.3 3876.4]]
[[ 606.1 1454.2]
 [1773.3 3876.4]]


In [69]:
print (x/y)
print (np.divide(x,y))

[[0.19963702 0.33282905]
 [0.29831388 0.49943246]]
[[0.19963702 0.33282905]
 [0.29831388 0.49943246]]


In [70]:
print (np.sqrt(x))

[[3.31662479 4.69041576]
 [4.79583152 6.63324958]]


In [71]:
print (np.exp(x))

[[5.98741417e+04 3.58491285e+09]
 [9.74480345e+09 1.28516001e+19]]


**Statistical operations**

In [75]:
a = 10 * np.random.randn(2,5)
print (a)
print(a.shape)

[[  4.03646211  -5.88237041 -10.80237192   7.85664795   9.78506928]
 [-10.12560953  12.53632614  12.38998017   3.02002239 -12.15895492]]
(2, 5)


In [77]:
print(a.mean())

1.0655201272830082


In [87]:
print(a.mean(axis=1))
print(np.mean(a,axis=1))

[0.9986874  1.13235285]
[0.9986874  1.13235285]


In [88]:
print(a.mean(axis=0))
print(np.mean(a,axis=0))

[-3.04457371  3.32697786  0.79380413  5.43833517 -1.18694282]
[-3.04457371  3.32697786  0.79380413  5.43833517 -1.18694282]


In [109]:
print(a.sum())
print(np.sum(a))

24
24


In [84]:
print(np.median(a,axis=1))

[4.03646211 3.02002239]


In [85]:
print(np.median(a,axis=0))

[-3.04457371  3.32697786  0.79380413  5.43833517 -1.18694282]


**Sorting**

In [93]:
unsorted = 10* np.random.randn(10)
print(unsorted)

[  4.54066361  -0.6792912  -14.90845647  10.14323538   3.17359225
   3.60591918  12.92429719  -6.51541829   4.91477036  10.59639146]


In [96]:
sorted = np.array(unsorted)
sorted.sort()
print(sorted)
print(unsorted)

[-14.90845647  -6.51541829  -0.6792912    3.17359225   3.60591918
   4.54066361   4.91477036  10.14323538  10.59639146  12.92429719]
[  4.54066361  -0.6792912  -14.90845647  10.14323538   3.17359225
   3.60591918  12.92429719  -6.51541829   4.91477036  10.59639146]


In [99]:
unsorted.sort()
print(unsorted)

[-14.90845647  -6.51541829  -0.6792912    3.17359225   3.60591918
   4.54066361   4.91477036  10.14323538  10.59639146  12.92429719]


**Unique element**

In [100]:
a = np.array([1,2,3,1,2,4,5,6])
print(np.unique(a))

[1 2 3 4 5 6]


**Set operations**

In [101]:
s1 = np.array(['desk','bulb','chair'])
s2 = np.array(['light','bulb','chair'])
print(s1)
print(s2)

['desk' 'bulb' 'chair']
['light' 'bulb' 'chair']


In [104]:
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [105]:
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'light']


In [106]:
print(np.setdiff1d(s1,s2))

['desk']


In [107]:
print(np.setdiff1d(s2,s1))

['light']


In [108]:
print(np.in1d(s1,s2))

[False  True  True]


**Broadcasting**

In [6]:
arr = np.zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
add_rows = np.array([1,2,3])
print(add_rows)

[1 2 3]


In [8]:
print(arr+add_rows)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [21]:
add_col = np.array([[2,2,2,2]])
print(add_col.shape)
add_col = add_col.T
print(add_col)
print(add_col.shape)

(1, 4)
[[2]
 [2]
 [2]
 [2]]
(4, 1)


In [20]:
print(arr+add_col)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [25]:
arr_scalar = 1
arr_s2 = np.array([2])
print(arr+arr_scalar)
print(arr+arr_s2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


**Random number generation**

In [34]:
y = np.random.normal(size=(1,5))
print(y)

[[ 1.31424798 -0.82136063 -1.04724859  0.58976135  0.04086777]]


In [36]:
z = np.random.randint(low=2, high=50, size=4)
print (z)

[14 27  5 18]


In [37]:
np.random.permutation(z)

array([ 5, 27, 14, 18])

In [38]:
np.random.uniform(size=4)

array([0.18759504, 0.52754605, 0.88397863, 0.14094913])

In [39]:
np.random.normal(size=4)

array([-1.19871181,  1.68523713, -1.30564739, -0.54221362])